// Code generated by "stringer -type State"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Starting-1]
	_ = x[Initializing-2]
	_ = x[Running-3]
	_ = x[Terminating-4]
	_ = x[Terminated-5]
}

const _State_name = "StartingInitializingRunningTerminatingTerminated"

var _State_index = [...]uint8{0, 8, 20, 27, 38, 48}

func (i State) String() string {
	i -= 1
	if i < 0 || i >= State(len(_State_index)-1) {
		return "State(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}
